In [35]:
print("hello")

hello

In [36]:
import random
def user_input():
    print("you have choices 1. snake 2. water 3. gun")
    choice = input("Enter your choice: ")
    while choice not in ['snake', 'water', 'gun']:
        print("Invalid choice, Please enter again.....")
        choice = input("Enter your choice again: ")
    return choice
def computer_input():
    return random.choice(['snake', 'water', 'gun'])
def detetmine_winner(user, computer):
    if user == computer:
        return "draw!!"
    elif((user == 'snake' and computer == 'water')or
            (user=='water' and computer == 'gun') or 
            (user == 'gun' and computer == 'snake')):
        return "you win!!"
    else:
        return "computer's win!!"
def play():
    print("welcome to the game of Snake, Water, Gun!")
    user_score = 0
    computer_score = 0
    rounds = int(input("how many rounds do you want to play? "))
    for i in range(1,rounds+1):
        print(f"\n---round {i}---\n")
        computer = computer_input()
        user = user_input()

        print(f"your choice is {user}")
        print(f"computer's choice is {computer}")

        result = detetmine_winner(user, computer)
        if(result == "draw!!"):
            print("It's a draw!")
        elif(result == "you win!!"):
            print("You win this round!")
            user_score += 1 
        else:
            print("Computer wins this round!")
            computer_score += 1
    print("\n---Final Scores---")
    print(f"score -> You: {user_score} | Computer: {computer_score}")
    if user_score > computer_score:
        print("Congratulations! You are winner!")
    elif user_score < computer_score:
        print("Computer is the winner!")
    else:
        print("It's draw!")
if __name__ == "__main__":
    play()

welcome to the game of Snake, Water, Gun!

---round 1---

you have choices 1. snake 2. water 3. gun
your choice is gun
computer's choice is water
Computer wins this round!

---Final Scores---
score -> You: 0 | Computer: 1
Computer is the winner!

Slicing

In [37]:
num = [10, 20, 30, 40, 50, 60]
print(num[1:4])
print(num[:3])
print(num[-3:])
print(num[::-1])
print(num[-2:-4])

[20, 30, 40]
[10, 20, 30]
[40, 50, 60]
[60, 50, 40, 30, 20, 10]
[]

In [38]:
import pandas as pd
data= {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 30, 22, 35, 28],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'Sales'],
    'Salary': [50000, 60000, 55000, 70000, 65000]

}

df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   30    Finance   60000
2  Charlie   22         IT   55000
3    David   35  Marketing   70000
4      Eva   28      Sales   65000

iloc in Pandas -> Access by integer based index positions

In [39]:
#Row at index 0
df.iloc[0]

Name          Alice
Age              24
Department       HR
Salary        50000
Name: 0, dtype: object

In [40]:
#First three rows
df.iloc[:3]

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   30    Finance   60000
2  Charlie   22         IT   55000

In [41]:
#last three rows
df.iloc[-3:]

      Name  Age Department  Salary
2  Charlie   22         IT   55000
3    David   35  Marketing   70000
4      Eva   28      Sales   65000

In [42]:
# Row 1, Column 3 
df.iloc[1,3]

np.int64(60000)

In [43]:
# Rows 1 to 3, Cloumns 1 to 2
df.iloc[1:4, 1:3]

   Age Department
1   30    Finance
2   22         IT
3   35  Marketing

In [44]:
#last row
df.iloc[-1]

Name            Eva
Age              28
Department    Sales
Salary        65000
Name: 4, dtype: object

loc in pandas -> Access by labels(row index, cloumn names)

In [45]:
#get row at index 2
df.loc[2]

Name          Charlie
Age                22
Department         IT
Salary          55000
Name: 2, dtype: object

In [46]:
# All rows, only name and Salary columns
df.loc[:, ['Name', 'Department', 'Salary']]

      Name Department  Salary
0    Alice         HR   50000
1      Bob    Finance   60000
2  Charlie         IT   55000
3    David  Marketing   70000
4      Eva      Sales   65000

In [47]:
#Filter rows where Salary is greater than 60000
df.loc[df['Salary']>60000]

    Name  Age Department  Salary
3  David   35  Marketing   70000
4    Eva   28      Sales   65000

In [48]:
#Update Salary for Bob
df.loc[1, 'Salary'] = 100000
df

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   30    Finance  100000
2  Charlie   22         IT   55000
3    David   35  Marketing   70000
4      Eva   28      Sales   65000

In [49]:
# Get names of all employees selary greater than 60000.
df.loc[df['Salary']>60000, 'Name']

1      Bob
3    David
4      Eva
Name: Name, dtype: object

In [50]:
# Retrieve the salary of the 2nd employee using iloc.
df.iloc[1,3]

np.int64(100000)

In [51]:
# Use .loc to get the department of Eva.
df.loc[df['Name']=='Eva', 'Department']

4    Sales
Name: Department, dtype: object

In [52]:
# Slice the DataFrame to get rows 0 to 2 and all columns using iloc
df.iloc[0:3, :]

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   30    Finance  100000
2  Charlie   22         IT   55000

In [53]:
# We can also change row lables using the index attribute.
df.index = ['A', 'B', 'C', 'D', 'E']
df

      Name  Age Department  Salary
A    Alice   24         HR   50000
B      Bob   30    Finance  100000
C  Charlie   22         IT   55000
D    David   35  Marketing   70000
E      Eva   28      Sales   65000