In [ ]:
import pandas as pd
import numpy as np

### Creating a Series

In [2]:
# Creating a Series
s = pd.Series([10, 20, 30, 40])
print(s)

# we can customize the indexing if we want
s = pd.Series([100, 200, 300],index=['a', 'b', 'c'])
print(s)

0    10
1    20
2    30
3    40
dtype: int64
a    100
b    200
c    300
dtype: int64

### Reading and Writing CSV Files

In [3]:
import pandas as pd
# Reading CSV:
df = pd.read_csv('churn.csv')   # Default: comma-separated
df

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,Female,33,12,6,21,Basic,Quarterly,947,14,1
64370,64371,37,Male,6,1,5,22,Standard,Annual,923,9,1
64371,64372,25,Male,39,14,8,30,Premium,Monthly,327,20,1
64372,64373,50,Female,18,19,7,22,Standard,Monthly,540,13,1
64373,64374,52,Female,45,15,9,25,Standard,Monthly,696,22,1

In [4]:
#You can also specify:
df1= pd.read_csv('churn.csv', header=None, names=['column1', 'column2'])
df1

,,,,,,,,,,column1,column2
CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
3,47,Male,27,10,2,29,Premium,Annual,757,21,0
4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
...,...,...,...,...,...,...,...,...,...,...,...
64370,45,Female,33,12,6,21,Basic,Quarterly,947,14,1
64371,37,Male,6,1,5,22,Standard,Annual,923,9,1
64372,25,Male,39,14,8,30,Premium,Monthly,327,20,1
64373,50,Female,18,19,7,22,Standard,Monthly,540,13,1
64374,52,Female,45,15,9,25,Standard,Monthly,696,22,1

In [5]:
# Writing to CSV:
df2= df.to_csv('output.csv', index=False)
df2

In [6]:
#🔹 index=False avoids saving the index as a separate column.
df3= df.to_csv('output1.csv')

### Handling missing data

In [ ]:
# Handling Missing Values
df.isnull()               # Detect
df.dropna()               # Drop rows with NaN
df.fillna(0)              # Fill NaNs with 0

In [8]:
df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', None],
    'Age': [25, None, 30]
})
df5

    Name   Age
0  Alice  25.0
1    Bob   NaN
2   None  30.0

In [9]:
print(df5.isnull())

    Name    Age
0  False  False
1  False   True
2   True  False

df.dropna() ❌
🧹 Purpose: Removes rows that contain any NaN values.

📌 Use Case: If missing data is small and can be safely discarded.

In [10]:
df5_cleaned = df5.dropna()
df5_cleaned

    Name   Age
0  Alice  25.0

df.fillna(0) ✅
🧯 Purpose: Fills missing values with a default value, e.g., 0.

📌 Use Case: When you prefer to impute instead of dropping rows.

In [11]:
df_filled = df5.fillna(0)
df_filled

    Name   Age
0  Alice  25.0
1    Bob   0.0
2      0  30.0

In [ ]:
# if you want to replace with avg. of any column
df10['Marks'] = df10['Marks'].fillna(df10['Marks'].mean())

### Iterating and Aggregations

In [12]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Marks': [95, 85, 92, 88, 76],
    'Grade': ['A', 'B', 'A', 'B', 'C']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name  Marks Grade
0    Alice     95     A
1      Bob     85     B
2  Charlie     92     A
3    David     88     B
4      Eva     76     C

In [13]:
#  Aggregation using groupby()
avg_marks_by_grade = df.groupby('Grade')['Marks'].mean()
print("\nAverage Marks by Grade:")
print(avg_marks_by_grade)

Average Marks by Grade:
Grade
A    93.5
B    86.5
C    76.0
Name: Marks, dtype: float64

### Converting Data
 #### To Dictionary / NumPy / List

In [14]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Marks': [95, 85, 92],
    'Grade': ['A', 'B', 'A']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# ✅ Convert to Dictionary
dict_data = df.to_dict()
print("\nConverted to Dictionary (default - columns):")
print(dict_data)

# ✅ Convert to NumPy Array
numpy_data = df.to_numpy()
print("\nConverted to NumPy Array:")
print(numpy_data)

Original DataFrame:
      Name  Marks Grade
0    Alice     95     A
1      Bob     85     B
2  Charlie     92     A

Converted to Dictionary (default - columns):
{'Name': {0: 'Alice', 1: 'Bob', 2: 'Charlie'}, 'Marks': {0: 95, 1: 85, 2: 92}, 'Grade': {0: 'A', 1: 'B', 2: 'A'}}

Converted to NumPy Array:
[['Alice' 95 'A']
 ['Bob' 85 'B']
 ['Charlie' 92 'A']]

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Marks': [95, 85, 92],
    'Grade': ['A', 'B', 'A']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
df

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Marks': [95, 85, 92],
 'Grade': ['A', 'B', 'A']}