### Slicing

In [ ]:

nums = [10, 20, 30, 40, 50, 60]

print(nums[1:4])   
print(nums[:3])    
print(nums[-3:])   
print(nums[::-1])

In [ ]:
print(nums[-4:-1])

In [ ]:
print(nums[-2:-4])

### Sample DataFrame

In [26]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Department': ['HR', 'Finance', 'Engineering', 'Marketing', 'Sales'],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}

df = pd.DataFrame(data)
df

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   30      Finance   60000
2  Charlie   35  Engineering   70000
3    David   40    Marketing   80000
4      Eva   45        Sales   90000

 ### .iloc[] in Pandas
*** Access by integer-based index positions ***

In [ ]:
# Row at index 0
#df.iloc[0]

# First 3 rows
#df.iloc[:3]

# Row 1, column 2 (Age of Bob)
#df.iloc[1, 1]

# Rows 1 to 3 and columns 1 to 2
 #df.iloc[1:4, 1:3]

# Last row
#df.iloc[-1]

### .loc[] in Pandas
Access by labels (row index, column names).

In [16]:
# Get row at index 2 (Charlie)
#df.loc[2]

# All rows, only Name and Salary
#df.loc[:, ['Name', 'Salary']]

# Rows 1 to 3 (inclusive) for Name and Department
#df.loc[1:3, ['Name', 'Department']]

# Filter rows where Salary > 60000
#df.loc[df['Salary'] > 60000]

# Update Age for Bob
#df.loc[1, 'Age'] = 31

In [17]:
df

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   31      Finance   60000
2  Charlie   35  Engineering   70000
3    David   40    Marketing   80000
4      Eva   45        Sales   90000

### Practice Problems

1. Get names of all employees older than 30.

2. Retrieve the salary of the 2nd employee using iloc.

3. Use .loc to get the department of Eva.

4. Slice the DataFrame to get rows 0 to 2 and all columns using iloc.

In [27]:
# 1 Get names of all employees older than 30.
df.loc[df['Age'] > 30, 'Name']

2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [28]:
# Retrieve the salary of the 2nd employee using iloc.
df.iloc[1, 3]

60000

In [30]:
#Use .loc to get the department of Eva.
df.loc[df['Name'] == 'Eva', 'Department'].values[0]

'Sales'

In [ ]:
#Slice the DataFrame to get rows 0 to 2 and all columns using iloc.
df.iloc[0:3, :]

### example to understand iloc and loc

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
})

In [19]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [20]:
#You can also change row labels:
df.index = ["a", "b", "c"]

In [21]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [24]:
#df.loc["b", "Age"]   # ✅ Works — label-based
#df.iloc[1, 1]        # ✅ Works — position-based
#df.iloc["b", "Age"]  # ❌ Error — 'b' is not a position!

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types