# 🧠 SQL to Pandas: A Hands-on Guide for AI/ML Students
This notebook introduces SQL basics and shows how to achieve the same functionality using Pandas.
We'll work with a sample `students.db` SQLite database.

In [1]:
# 📦 Setup: Load packages and create a SQLite database
import sqlite3
import pandas as pd
import numpy as np

# Create a connection
conn = sqlite3.connect('students.db')

# Create a sample table
conn.execute('''CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    math_score INTEGER,
    english_score INTEGER,
    grade TEXT
);''')

# Insert sample data
conn.execute("DELETE FROM students;")
students_data = [
    (1, 'Alice', 85, 78, 'A'),
    (2, 'Bob', 67, 88, 'B'),
    (3, 'Charlie', 92, 95, 'A'),
    (4, 'David', 58, 62, 'C'),
    (5, 'Eva', 76, 83, 'B')
]
conn.executemany("INSERT INTO students VALUES (?, ?, ?, ?, ?);", students_data)
conn.commit()

## 🔍 SQL Queries: Examples
Let’s run some SQL queries and then replicate the same logic using Pandas.

In [2]:
# Run SQL query: Select all students
query = "SELECT * FROM students;"
df_sql = pd.read_sql_query(query, conn)
df_sql

   id     name  math_score  english_score grade
0   1    Alice          85             78     A
1   2      Bob          67             88     B
2   3  Charlie          92             95     A
3   4    David          58             62     C
4   5      Eva          76             83     B

## 🔁 Pandas Equivalent of SQL Queries
Let’s load the same data into Pandas and perform equivalent operations.

In [3]:
# Load data into Pandas
df = pd.read_sql_query("SELECT * FROM students", conn)
df.head()

   id     name  math_score  english_score grade
0   1    Alice          85             78     A
1   2      Bob          67             88     B
2   3  Charlie          92             95     A
3   4    David          58             62     C
4   5      Eva          76             83     B

### 🎯 Example 1: Students scoring above 80 in Math (SQL vs Pandas)

In [4]:
# SQL Equivalent
pd.read_sql_query("SELECT * FROM students WHERE math_score > 80", conn)

   id     name  math_score  english_score grade
0   1    Alice          85             78     A
1   3  Charlie          92             95     A

In [5]:
# Pandas Equivalent
df[df['math_score'] > 80]

   id     name  math_score  english_score grade
0   1    Alice          85             78     A
2   3  Charlie          92             95     A

### 📊 Example 2: Group by grade and count students

In [6]:
# SQL Equivalent
pd.read_sql_query("SELECT grade, COUNT(*) as student_count FROM students GROUP BY grade", conn)

  grade  student_count
0     A              2
1     B              2
2     C              1

In [7]:
# Pandas Equivalent
df.groupby('grade').size().reset_index(name='student_count')

  grade  student_count
0     A              2
1     B              2
2     C              1

## Summary Task: Convert the following SQL to Pandas:
```sql
SELECT name, english_score FROM students WHERE english_score > 80 ORDER BY english_score DESC;
```
**Write the equivalent Pandas code below:**

In [8]:
# Your answer here
df[df['english_score'] > 80][['name', 'english_score']].sort_values(by='english_score', ascending=False)

      name  english_score
2  Charlie             95
1      Bob             88
4      Eva             83